config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  resources :users, only: [:show, :edit, :update]
  get '/user_review', to: 'reviews#show_user_reviews', as: 'user_review'
  get '/admin', to: 'admin#index', as: 'admin'
  resources :bird_images
  resources :species
  resources :birds do
    resources :reviews
    resources :replies
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :review
  belongs_to :bird

  scope :all_replies, ->{order(created_at: :desc)}

  validates :content, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :find_bird, only: [:index, :create, :show, :edit, :update, :destroy]
  # before_action :find_review, only: [:index, :create, :show, :edit, :update, :destroy]
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    # @replies = @review.replies.all_replies
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = current_user.replies.build
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = current_user.replies.build(reply_params)
    if @reply.save
      flash[:success] = "Thank you for your reply."
      redirect_to :back
    else
      if @reply.errors.any?
        flash[:warning] = "Reply can't be blank."
      else
        flash[:warning] = "Some errors occured"
      end
      redirect_to :back
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_reply
    @reply = Reply.find_by id: params[:id]
    return if @reply
    redirect_to :back
  end

  def find_bird
    @bird = Bird.find_by id: params[:bird_id]
    return if @bird
    redirect_to :back
  end

  def find_review
    @review = Review.find_by id: params[:review_id]
    return if @review
    redirect_to :back
  end

  def reply_params
    params.require(:reply).permit(:content, :review_id)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for [@bird, Reply.new] do |f| %>
  <div style="padding-top: 25px">
    <%= f.hidden_field :review_id, value: review_id %>
    <div class="review-form-text">
      <%= f.text_area :content, class: "form-control" %>
    </div>
    <div class="review-form-submit">
      <%= f.submit "返信", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/replies/_reply.html.erb
<div class="record" id="record-#{review.id}">
  <li>
    <%= avatar_for(reply.user) %>
    <strong><%= reply.user.user_name %></strong> は&ensp;
    <span><%= reply.updated_at.localtime.strftime("%d-%m-%Y, %H:%M") %> に返信しました</span><br>
    <span><%= reply.content %></span><br>
  </li>
</div>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.content %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @reply.content %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>