config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  resources :users, only: [:show, :edit, :update]
  get '/user_review', to: 'reviews#show_user_reviews', as: 'user_review'
  get '/admin', to: 'admin#index', as: 'admin'
  resources :bird_images
  resources :species
  resources :birds do
    resources :reviews
    resources :replies
  end

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]
  before_action :set_bird_images, only: [:show, :index]
  # GET /species
  # GET /species.json
  def index
    @species = Species.all.order(:species_name).page(params[:page]).per(6)
  end

  # GET /species/1
  # GET /species/1.json
  def show
    @birds = Bird.where(species_id:@species.id).order(:bird_name).page(params[:page]).per(6)
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
    @birds = Bird.where(species_id:@species.id)
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    def set_bird_images
      @bird_images = BirdImage.joins(bird: :species)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:species_name, :species_info, :min_price, :max_price)
    end
end

app/views/species/_form.html.erb
<div id="colorlib-page">
  <div id="colorlib-main-log">
    <div id="colorlib-log">
      <div id="colorlib-log-detail">
        <%if current_user.user_role == 1 %>
          <h2><b>新しい種類</b></h2>

          <%= form_for(@species) do |f| %>
            <% if @species.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@species.errors.count, "error") %> prohibited this bird from being saved:</h2>

                <ul>
                  <% @species.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="field">
              <%= f.label :species_name, "名" %><br>
              <%= f.text_field :species_name %>
            </div>
            <div class="field">
              <%= f.label :species_info, "情報" %><br>
              <%= f.text_area :species_info %>
            </div>
            <div class="actions">
              <%= f.submit "作成"%>
            </div>
            <%= link_to 'バック', species_index_path, method: :get%>
          <% end %>
        <% else %>
          <h1>編集する権限を持っていません </h1>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/species/_species_index.html.erb
<%= paginate @species %>
<% @species.each_slice(3) do |specie_row| %>
  <div class="row">
    <% specie_row.each do |specie| %>
      <div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="blog-entry">
          <%= link_to specie, method: :get do %>
            <div class="blog-img">
              <div class = "bird_cell" >
                <%=
                Bird.where(species_id:specie.id).count > 0 ?
                  image_tag(@bird_images.where(bird_id:(Bird.where(species_id:specie.id).first).id).first.image,   :width => "100%")
                    : image_tag("no_image.png", :width => "100%")
                %>
              </div>
            </div>
          <% end %>
          <div class="desc">
            <span>
              <small>
                <i class="icon-bubble3"></i>
                <%= specie.review_count %>
              </small> |
              <small>
                <i class="icon-star2"></i>
                <%= specie.rating %>
              </small>
            </span>
            <h3><%= link_to specie.species_name, specie, method: :get %></h3>
            <p><%=specie.species_info%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= paginate @species %>

app/views/species/_species_show.html.erb
<h2 class="colorlib-heading">鳥のリスト</h2>
<% @birds.each_slice(3) do |bird_row| %>
  <div class="row">
    <% bird_row.each do |bird| %>
      <div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="blog-entry">
          <%= link_to bird do %>
            <div class="blog-img">
              <div class = "bird_cell" >
                <%=
                  @bird_images.where(bird_id:bird.id).exists? ?
                    image_tag(@bird_images.where(bird_id:bird.id).first.image,   :width => "100%")
                      : image_tag("no_image.png", :width => "100%")
                 %>
              </div>
            </div>
          <% end %>
          <div class="desc">
            <span>
              <small><%= bird.species.species_name %></small> |
              <small>
                <i class="icon-bubble3"></i>
                <%= bird.reviews.count %>
              </small> |
              <small>
                <i class="icon-star2"></i>
                <%= bird.rating %>
              </small>
            </span>
            <h3><%= link_to bird.bird_name, bird, method: :get%></h3>
            <p><%=bird.bird_info%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= paginate @birds %>

app/views/species/edit.html.erb
<div id="colorlib-page-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-blog">
      <div class="colorlib-narrow-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
            <%if current_user.user_role == 1 %>
              <div class="container">
                <h1>種類編集</h1>
                <%= form_for(@species, html: {multipart: true}) do |f| %>
                  <hr>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                      <div class="about-img">
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                          <!-- Indicators -->
                          <ol class="carousel-indicators">
                            <% BirdImage.where(bird_id: @birds.ids).each_with_index do |bird_image, index| %>
                              <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
                            <% end %>
                          </ol>

                          <!-- Wrapper for slides -->

                          <div class="carousel-inner" role="listbox">
                            <% BirdImage.where(bird_id: @birds.ids).each_with_index do |bird_image, index| %>
                              <div class="item <%= index == 0 ? 'active' : '' %>">
                                <div class="bird_cell">
                                  <%= image_tag(bird_image.image, :width => "100%", :height => "510px") %>
                                </div>
                              </div>
                            <% end %>
                          </div>

                          <!-- Left and right controls -->
                          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                      </div>
                    </div>

                    <!-- edit form column -->
                    <div class="col-md-6 personal-info">
                      <h3>種類情報</h3>
                      <%= f.label :species_name, "名" %>
                      <%= f.text_field :species_name, class: 'form-control' %>

                      <%= f.label :species_info, "情報" %>
                      <%= f.text_field :species_info, class: 'form-control' %>

                      <div style="padding-top: 30px">
                        <%= f.submit "変更内容を保存", class: "btn btn-primary" %>
                      </div>
                    </div>
                <% end %>
                </div>
              </div>
            <% else %>
              <h1>編集する権限を持っていません </h1>
            <% end %>


            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/species/index.html.erb
<div id="colorlib-page-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-blog">
      <div class="colorlib-narrow-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
            <span class="heading-meta-kanji">種類</span>
            <h2 class="colorlib-heading">種類概要</h2>
            <% if user_signed_in? %>
              <% if current_user.user_role==1 %>
                <%= link_to "種類登録", new_species_path, method: :get, class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <br>
        <div class="animate-box" data-animate-effect="fadeInLeft">
          <h2 class="heading-results">
            種類の数: <%= @species.total_count %>
          </h2>
          <%= render partial: "species/species_index", layout: "species/species_index" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/species/new.html.erb
<%= render 'form' %>

app/views/species/show.html.erb
<div id="colorlib-page-double-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-about">
      <div class="colorlib-narrow-content">
        <div class="col-md-6">
          <div class="about-img">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <% BirdImage.where(bird_id: @birds.ids).each_with_index do |bird_image, index| %>
                  <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
                <% end %>
              </ol>

              <!-- Wrapper for slides -->

              <div class="carousel-inner" role="listbox">
                <% BirdImage.where(bird_id: @birds.ids).each_with_index do |bird_image, index| %>
                  <div class="item <%= index == 0 ? 'active' : '' %>">
                    <div class="bird_cell">
                      <%= image_tag(bird_image.image, :width => "100%", :height => "510px") %>
                    </div>
                  </div>
                <% end %>
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="about-desc">
            <h2 class="colorlib-heading"><%= @species.species_name %></h2>
            <div class = "review-rating-big">
               <strong><%= @species.review_count %> ユーザは <%= @species.species_name %> を評価しました</strong>
            </div>
            <div class = "review-rating-big">
              <div class="update-rating"><strong>平均スコア: <%= @species.rating %>/5</strong></div>
              <%= render partial: "reviews/rating", locals: {rating: @species.rating} %>
            </div>
            <p><%= @species.species_info %></p>
          </div>
          <div class="about-desc">
            <span class="heading-meta-kanji">最小値段:</span>
            <h2>¥ <%= @birds.minimum("bird_price") %>‎</h2>
          </div>
          <div class="about-desc">
            <span class="heading-meta-kanji">最大値段:</span>
            <h2>¥ <%= @birds.maximum("bird_price") %>‎</h2>
          </div>
          <% if user_signed_in? %>
          <% if current_user.user_role==1 %>
            <%= link_to "種類編集", edit_species_path(@species), method: :get, class: "btn btn-primary" %>
          <% end %>
          <% end %>
        </div>
        <div class="colorlib-about", style =  "padding-top: 0px">
          <p></p>
          <%= render partial: "species/species_show", layout: "species/species_show" %>
        </div>
      </div>
    </div>
  </div>
</div>