config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations"}
  resources :users, only: [:show, :edit, :update]
  get '/user_review', to: 'reviews#show_user_reviews', as: 'user_review'
  get '/admin', to: 'admin#index', as: 'admin'
  resources :bird_images
  resources :species
  resources :birds do
    resources :reviews
    resources :replies
  end

end

app/models/bird.rb
class Bird < ActiveRecord::Base
  belongs_to  :species
  has_many    :bird_images,   dependent: :destroy
  has_many    :reviews,       dependent: :destroy
  has_many    :replies,       dependent: :destroy

  scope :by_name, ->(search){where("bird_name LIKE ?", "%#{search}%")}

  def rating
    if reviews.empty?
      0
    else
      (reviews.average(:rating)/10).round(1)
    end
  end

  def rating_easy
    if reviews.empty?
      0
    else
      (reviews.average(:rating_easy)/10).round(1)
    end
  end

  def rating_price
    if reviews.empty?
      0
    else
      (reviews.average(:rating_price)/10).round(1)
    end
  end


  def review_user_present? id
    reviews.find_by(user: id).present?
  end

  def review_user id
    reviews.find_by(user: id)
  end

  def review_count
    reviews.count
  end
  mount_uploader :bird_voice, VoiceUploader
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: [:show, :edit, :update, :destroy]

  def index
    @bird_images = BirdImage.joins(:bird)
    @q = Bird.search(params[:q])
    @birds = @q.result.includes(:species, :reviews).page(params[:page]).per(6)
  end

  def show
    @bird_images = BirdImage.joins(:bird)
    @reviews = @bird.reviews.all_comments.page(params[:page]).per(6)
    @slideshow_selected_image_index = 1
  end

  def new
    @bird = Bird.new
    @species = Species.all
  end

  def edit
    @species = Species.all
  end

  def create
    @bird = Bird.new(bird_params)
    respond_to do |format|
      if @bird.save
        format.html { redirect_to @bird, notice: 'Bird was successfully created.' }
        format.json { render :show, status: :created, location: @bird }
      else
        format.html { render :new }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bird.update(bird_params)
        flash[:success] = "Bird profile updated"
        format.html { redirect_to @bird, notice: 'Bird was successfully updated.' }
        format.json { render :show, status: :ok, location: @bird }
      else
        flash[:error] = "Update failed! Something went wrong!"
        format.html { render :edit }
        format.json { render json: @bird.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bird.destroy
    respond_to do |format|
      format.html { redirect_to birds_url, notice: 'Bird was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_bird
    @bird = Bird.find(params[:id])
  end

  def bird_params
    params.require(:bird).permit(:bird_name, :bird_info, :bird_price, :bird_voice, :species_id)
  end

end

app/helpers/birds_helper.rb
module BirdsHelper
  def options_for_species
    Species.pluck(:species_name,:id)
  end

end

app/views/birds/_bird_index.html.erb
<% @birds.each_slice(3) do |bird_row| %>
  <div class="row">
    <% bird_row.each do |bird| %>
      <div class="col-md-4 col-sm-6 animate-box" data-animate-effect="fadeInLeft">
        <div class="blog-entry">
          <%= link_to bird do %>
            <div class="blog-img">
              <div class = "bird_cell" >
                <%=
                  @bird_images.where(bird_id:bird.id).exists? ?
                    image_tag(@bird_images.where(bird_id:bird.id).first.image,   :width => "100%")
                      : image_tag("no_image.png", :width => "100%")
                %>
              </div>
            </div>
          <% end %>
          <div class="desc">
            <span>
              <small><%= bird.species.species_name %></small> |
              <small>
                <i class="icon-bubble3"></i>
                <%= bird.reviews.count %>
              </small> |
              <small>
                <i class="icon-star2"></i>
                <%= bird.rating %>
              </small>
            </span>
            <h3><%= link_to bird.bird_name, bird, method: :get%></h3>
            <p><%=bird.bird_info%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<%= paginate @birds %>

app/views/birds/_form.html.erb
<div id="colorlib-page">
  <div id="colorlib-main-log">
    <div id="colorlib-log">
      <div id="colorlib-log-detail">
        <h2><b>新しい鳥</b></h2>

        <%= form_for(@bird) do |f| %>
          <% if @bird.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@bird.errors.count, "error") %> prohibited this bird from being saved:</h2>

              <ul>
                <% @bird.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :bird_name, "名" %><br>
            <%= f.text_field :bird_name %>
          </div>
          <div class="field">
            <%= f.label :bird_info, "情報" %><br>
            <%= f.text_area :bird_info %>
          </div>
          <div class="field">
            <%= f.label :bird_price, "値段"%><br>
            <%= f.number_field :bird_price %>
          </div>
          <div class="field">
            <%= f.label :bird_voice, "声" %>
            <%= f.file_field :bird_voice ,class:'upload-btn'%>
          </div>
          <div class="field">
            <%= f.label :species_id, "種類" %><br>
            <% options = options_from_collection_for_select(@species, 'id', 'species_name') %>
            <%= f.select :species_id,  options %>
          </div>
          <div class="actions">
            <%= f.submit "作成"%>
          </div>
          <%= link_to 'バック', birds_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/birds/edit.html.erb
<div id="colorlib-page-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-blog">
      <div class="colorlib-narrow-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
            <%if current_user.user_role == 1 %>
              <div class="container">
                <h1>鳥編集</h1>
                <%= form_for(@bird, html: {multipart: true}) do |f| %>
                  <hr>
                  <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                      <div class="about-img">
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                          <!-- Indicators -->
                          <ol class="carousel-indicators">
                            <% BirdImage.where(bird_id: @bird.id).each_with_index do |bird_image, index| %>
                              <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
                            <% end %>
                          </ol>

                          <!-- Wrapper for slides -->

                          <div class="carousel-inner" role="listbox">
                            <% BirdImage.where(bird_id: @bird.id).each_with_index do |bird_image, index| %>
                              <div class="item <%= index == 0 ? 'active' : '' %>">
                                <div class="bird_cell">
                                  <%= image_tag(bird_image.image, :width => "100%", :height => "510px") %>
                                </div>
                              </div>
                            <% end %>
                          </div>

                          <!-- Left and right controls -->
                          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                      </div>
                    </div>

                    <!-- edit form column -->
                    <div class="col-md-6 personal-info">
                      <h3>Bird info</h3>
                      <%= f.label :bird_name, "名" %>
                      <%= f.text_field :bird_name, class: 'form-control' %>

                      <%= f.label :bird_info, "情報" %>
                      <%= f.text_field :bird_info, class: 'form-control' %>

                      <%= f.label :bird_price, "値段" %>
                      <%= f.number_field  :bird_price ,class:'form-control'%>

                      <%= f.label :species_id, "種類" %><br>
                      <% options = options_from_collection_for_select(@species, 'id', 'species_name') %>
                      <%= f.select :species_id,  options %><br>

                      <%= f.label :bird_voice, "声" %>
                      <%= f.file_field :bird_voice ,class:'upload-btn'%>
                      <div style="padding-top: 30px">
                        <%= f.submit "変更内容を保存", class: "btn btn-primary" %>
                      </div>
                    </div>
                <% end %>
                </div>
              </div>
            <% else %>
              <h1>編集する権限を持っていません </h1>
            <% end %>


            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/birds/index.html.erb
<div id="colorlib-page-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-blog">
      <div class="colorlib-narrow-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
            <% if params[:q] %>
              <h2 class="colorlib-heading">結果</h2>
            <% else %>
              <span class="heading-meta-kanji">鳥</span>
              <h2 class="colorlib-heading">鳥概要</h2>
            <% end %>

            <%= content_tag :th, sort_link(@q, :bird_name, "名によるソート", {}, { class: "btn btn-primary", method: :get }) %>
            <%= button_tag "詳細検索", class: "btn btn-primary", data: {toggle: "collapse", target: "#advance-search"} %>

            <% if user_signed_in? %>
              <% if current_user.user_role==1 %>
                <%= link_to "鳥登録", new_bird_path, method: :get, class: "btn btn-primary" %>
              <% end %>
            <% end %>

            <div class="collapse" id="advance-search">
              <%= search_form_for @q do |f| %>
                <div class="row">
                  <div class="col-md-6"><br>
                    <%= f.label "鳥がある", class: "advanced-label" %>
                  </div><br>
                  <div class="col-md-6">
                    <%= f.search_field :bird_name_cont, class: "search-advanced-form" %>
                  </div>
                </div><br>
                <div class="row">
                  <div class="col-md-6">
                    <%= f.label "種類がある", class: "advanced-label" %>
                  </div>
                  <div class="col-md-6">
                    <%= f.search_field :species_species_name_cont, class: "search-advanced-form" %>
                  </div>
                </div><br>
                <div class="row">
                  <div class="col-md-6">
                    <%= f.label "最小値段", class: "advanced-label" %>
                  </div>
                  <div class="col-md-6">
                    <%= f.search_field :bird_price_gteq, class: "search-advanced-form" %>
                  </div><br>
                </div><br>
                <div class="row">
                  <div class="col-md-6">
                    <%= f.label "最大値段", class: "advanced-label" %>
                  </div>
                  <div class="col-md-6">
                    <%= f.search_field :bird_price_lteq, class: "search-advanced-form" %>
                  </div>
                </div>
                <%= button_tag "Search", type: "submit", class: "btn btn-primary" do %>
                  <i class="fa fa-search" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <br>
        <div class="animate-box" data-animate-effect="fadeInLeft">
          <% if @birds.present? %>
            <h2 class="heading-results">
              <%= @birds.total_count %>
              <% if @birds.total_count == 1 %> 結果<% else %> 結果<% end %>
            </h2>
            <%= render partial: "birds/bird_index", layout: "birds/bird_index" %>
          <% else %>
            <p class="heading-results">ごめんなさい。結果がありません。他のキーワードを入力して見てください。</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/birds/show.html.erb
<div id="colorlib-page-double-top-padding">
  <div id="colorlib-main">
    <div class="colorlib-about">
      <div class="colorlib-narrow-content">
        <div class="col-md-6">
          <div class="about-img">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <% BirdImage.where(bird_id: @bird.id).each_with_index do |bird_image, index| %>
                  <li data-target="#myCarousel" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
                <% end %>
              </ol>

              <!-- Wrapper for slides -->

              <div class="carousel-inner" role="listbox">
                <% if BirdImage.where(bird_id: @bird.id).count == 0 %>
                  <%= image_tag("anon_bird.png", :width => "100%", :height => "510px") %>
                <% else %>
                  <% BirdImage.where(bird_id: @bird.id).each_with_index do |bird_image, index| %>
                    <div class="item <%= index == 0 ? 'active' : '' %>">
                      <div class="bird_cell">
                        <%= image_tag(bird_image.image, :width => "100%", :height => "510px") %>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="about-desc">

            <%= link_to @bird.species, method: :get do %>
              <span class="heading-meta"><%= @bird.species.species_name %></span>
            <% end %>
            <h2 class="colorlib-heading"><%= @bird.bird_name %></h2>

            <div class="review-rating-big">
              <div class="update-rating"><strong>平均スコア: <%= ((@bird.rating+@bird.rating_easy+@bird.rating_price)/3).round(1) %>/5</strong></div>
              <%= render partial: "reviews/rating", locals: {rating: ((@bird.rating+@bird.rating_easy+@bird.rating_price)/3).round(1) } %>

            </div>
            <div class="about-desc">
            <div class = 'col-md-1'>声:</div>
            <div class = 'col-md-3'><%= render partial: "reviews/rating", locals: {rating: @bird.rating } %></div>
            <div class = 'col-md-1'>価:</div>
            <div class = 'col-md-3'><%= render partial: "reviews/rating", locals: {rating: @bird.rating_price } %></div>
            <div class = 'col-md-1'>易:</div>
            <div class = 'col-md-3'><%= render partial: "reviews/rating", locals: {rating: @bird.rating_easy } %></div>
            </div>
          </div>
            <div class="about-desc">
<br><br>
            <p><%= @bird.bird_info %></p>

            <span class="heading-meta-kanji">値段:</span>
            <h2>¥ <%= @bird.bird_price %>‎</h2>

            <span class="heading-meta-kanji">音声:</span>
            <audio controls>
              <source src=<%= asset_path(@bird.bird_voice) %> type="audio/mpeg">
              声のデータがありません
            </audio>
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
          <% if current_user.user_role == 1 %>

            <%#= link_to "Upload image", new_bird_image_path(), method: :get, class: "btn btn-primary" %>

            <%= link_to "鳥編集", edit_bird_path(@bird), method: :get, class: "btn btn-primary" %>
            <%= link_to "鳥削除", @bird, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>

          <% end %>
        <% end %>

        <div class="colorlib-about" , style="padding-top: 0px">
          <%= render partial: "birds/hexa_review", layout: "birds/hexa_review" %>
          <div id="review-area">
            <% if user_signed_in? %>
              <% if @bird.review_user_present?(current_user.id) %>
                <%= render partial: "reviews/update_form" %>
              <% else %>
                <%= render partial: "reviews/form" %>
              <% end %>
            <% end %>
          </div>

          <div class="container">
            <strong><%= @bird.review_count %> ユーザは <%= @bird.bird_name %> を評価しました</strong>
            <%= paginate @reviews %>
            <ul class="review-list">
              <%= render @reviews %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>